version: "3.2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kabum_db
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./docker/backend/config/nginx.conf:/etc/nginx/conf.d/site.conf
      - ./app/backend:/backend
    links:
      - backend
  backend:
    build: ./docker/backend
    container_name: backend
    restart: always
    depends_on: 
      - mysql
    volumes:
      - ./app/backend:/backend
    links:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: kabum_db
      DATABASE_USER: root
      DATABASE_PASS: secret
  frontend:
    build: ./docker/frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app/frontend:/frontend
    links:
      - nginx